language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-7 build-essential cmake wget
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # CMake > 3.12
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.0-rc1-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.17.0-rc1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.0-rc1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - g++ --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON ..
  - make all

script:
  - ./tests/lgeometric_tst 
